### ISSUE TITLE
Are you missing an assembly reference? Error appears after import socket.io-unity.unitypackage v1.0.1

### ISSUE THREAD

**Issue by QuantumPixelForge** [Rocher0724/socket.io-unity#16]
Hi,

I have 14 errors after I imported package from [https://github.com/Rocher0724/socket.io-unity/releases](https://github.com/Rocher0724/socket.io-unity/releases) v1.0.1

Those are 2 files where errors appears: DynamicReflectionDelegateFactory and ILGeneratorExtensions.

`Assets/Plugins/Socket/Newtonsoft.Json/Utilities/DynamicReflectionDelegateFactory.cs(8,38): error CS0234: The type or namespace name 'Label' does not exist in the namespace 'System.Reflection.Emit' (are you missing an assembly reference?)`

`Assets/Plugins/Socket/Newtonsoft.Json/Utilities/ILGeneratorExtensions.cs(7,42): error CS0246: The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)`

Unity version: **2019.4.11f**

**Comment by delmaass** [comment]
Hi biopowder,

I also experimented this issue.
To solve those errors, I had to go into : Edit > Project Settings >Player > API Compatibility Level"
Then I changed it to .NET 4.x.
I also had to install "Unity Reflector" from the Package Manager because other errors came after.

Hope this helps !

**Comment by QuantumPixelForge** [comment]
Thanks, didn't know about this option :) I don't have errors now, but its not working for me, I see only "Start" message. Will try to figure out, whats wrong. Thx one more time 🥇

**Comment by QuantumPixelForge** [comment]
its not working with Socket IO 4.0.0, only with 2 and less...

**Comment by delmaass** [comment]
Yes, you have to downgrade Socket.io to 2.4.0 (last stable 2.x version)
